language: node_js
node_js:
- 6.9.1
env:
  - CI=false
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_55f7e8291359_key -iv $encrypted_55f7e8291359_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
before_script:
- git config --global user.name 'Sabrina Luo'
- git config --global user.email 'luohaojing@gmail.com'
script:
- npm run build
after_success:
- npm run deploy
